public enum TokenType {
    START, END, INT, BOOLEAN, DOUBLE, WHILE, IF, ELSE, IDENTIFICADOR, NUMERO,
    OPERADOR, OPERADOR_RELACIONAL, IGUAL, PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO,
    LLAVE_IZQUIERDA, LLAVE_DERECHA, PUNTO_COMA, DESCONOCIDO,PR,STRING,TEXTO
}
